class Charge < ApplicationRecord
  include RefreshesDashboard
  include RefreshesMemberBalance

  belongs_to :member
  belongs_to :attendance, optional: true

  enum :charge_type, {
    late_fee: "late_fee",
    no_show_fee: "no_show_fee",
    uniform: "uniform",
    activity: "activity",
    membership: "membership",
    equipment: "equipment",
    other: "other"
  }

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :charge_type, presence: true

  scope :recent, -> { order(created_at: :desc) }

  # Auto charges are generated by attendance; manual ones are created by an admin.
  def automatic?
    attendance_id.present?
  end
end
